server:
  port: 8888
spring:
  application:
    name: muses-demo
  output:
    ansi:
      enabled: always
muses:
  base:
    header:
      sysCode: muses
logging:
  level:
    com.github.stazxr.muses: debug